# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 230)
        MainWindow.setMinimumSize(QtCore.QSize(420, 230))
        MainWindow.setMaximumSize(QtCore.QSize(420, 230))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 10, 431, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"  qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
"  border: 1px solid gray;\n"
"}")
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(0, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(70, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setGeometry(QtCore.QRect(140, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.button_div = QtWidgets.QPushButton(self.centralwidget)
        self.button_div.setGeometry(QtCore.QRect(210, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_div.setFont(font)
        self.button_div.setObjectName("button_div")
        self.button_eq = QtWidgets.QPushButton(self.centralwidget)
        self.button_eq.setGeometry(QtCore.QRect(350, 190, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_eq.setFont(font)
        self.button_eq.setObjectName("button_eq")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(350, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_clear.setFont(font)
        self.button_clear.setObjectName("button_clear")
        self.button_lbracket = QtWidgets.QPushButton(self.centralwidget)
        self.button_lbracket.setGeometry(QtCore.QRect(280, 110, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_lbracket.setFont(font)
        self.button_lbracket.setObjectName("button_lbracket")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(140, 110, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.button_rbracket = QtWidgets.QPushButton(self.centralwidget)
        self.button_rbracket.setGeometry(QtCore.QRect(350, 110, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_rbracket.setFont(font)
        self.button_rbracket.setObjectName("button_rbracket")
        self.button_mult = QtWidgets.QPushButton(self.centralwidget)
        self.button_mult.setGeometry(QtCore.QRect(210, 110, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_mult.setFont(font)
        self.button_mult.setStyleSheet("")
        self.button_mult.setObjectName("button_mult")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(0, 110, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(70, 110, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.button_lg = QtWidgets.QPushButton(self.centralwidget)
        self.button_lg.setGeometry(QtCore.QRect(280, 190, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_lg.setFont(font)
        self.button_lg.setObjectName("button_lg")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(140, 150, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.button_pow_x_y = QtWidgets.QPushButton(self.centralwidget)
        self.button_pow_x_y.setGeometry(QtCore.QRect(350, 150, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_pow_x_y.setFont(font)
        self.button_pow_x_y.setObjectName("button_pow_x_y")
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(210, 150, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_minus.setFont(font)
        self.button_minus.setObjectName("button_minus")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(0, 150, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(70, 150, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.button_root2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_root2.setGeometry(QtCore.QRect(280, 150, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_root2.setFont(font)
        self.button_root2.setObjectName("button_root2")
        self.button_fac = QtWidgets.QPushButton(self.centralwidget)
        self.button_fac.setGeometry(QtCore.QRect(140, 190, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_fac.setFont(font)
        self.button_fac.setObjectName("button_fac")
        self.button_del = QtWidgets.QPushButton(self.centralwidget)
        self.button_del.setGeometry(QtCore.QRect(280, 70, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_del.setFont(font)
        self.button_del.setObjectName("button_del")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(210, 190, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_plus.setFont(font)
        self.button_plus.setObjectName("button_plus")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(0, 190, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        self.button_comma = QtWidgets.QPushButton(self.centralwidget)
        self.button_comma.setGeometry(QtCore.QRect(70, 190, 70, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_comma.setFont(font)
        self.button_comma.setObjectName("button_comma")
        self.button_help = QtWidgets.QPushButton(self.centralwidget)
        self.button_help.setGeometry(QtCore.QRect(0, 50, 20, 20))
        self.button_help.setObjectName("button_help")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionprofiling = QtWidgets.QAction(MainWindow)
        self.actionprofiling.setObjectName("actionprofiling")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "0"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_7.setShortcut(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_8.setShortcut(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_9.setShortcut(_translate("MainWindow", "9"))
        self.button_div.setText(_translate("MainWindow", "/"))
        self.button_div.setShortcut(_translate("MainWindow", "/"))
        self.button_eq.setText(_translate("MainWindow", "="))
        self.button_eq.setShortcut(_translate("MainWindow", "Return"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))
        self.button_clear.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.button_lbracket.setText(_translate("MainWindow", "("))
        self.button_lbracket.setShortcut(_translate("MainWindow", "("))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_6.setShortcut(_translate("MainWindow", "6"))
        self.button_rbracket.setText(_translate("MainWindow", ")"))
        self.button_rbracket.setShortcut(_translate("MainWindow", ")"))
        self.button_mult.setText(_translate("MainWindow", "*"))
        self.button_mult.setShortcut(_translate("MainWindow", "*"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_4.setShortcut(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_5.setShortcut(_translate("MainWindow", "5"))
        self.button_lg.setText(_translate("MainWindow", "Ln"))
        self.button_lg.setShortcut(_translate("MainWindow", "L"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_3.setShortcut(_translate("MainWindow", "3"))
        self.button_pow_x_y.setText(_translate("MainWindow", "^"))
        self.button_pow_x_y.setShortcut(_translate("MainWindow", "^"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_minus.setShortcut(_translate("MainWindow", "-"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_1.setShortcut(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_2.setShortcut(_translate("MainWindow", "2"))
        self.button_root2.setText(_translate("MainWindow", "√"))
        self.button_root2.setShortcut(_translate("MainWindow", "R"))
        self.button_fac.setText(_translate("MainWindow", "!"))
        self.button_fac.setShortcut(_translate("MainWindow", "!"))
        self.button_del.setText(_translate("MainWindow", "C"))
        self.button_del.setShortcut(_translate("MainWindow", "Backspace"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_plus.setShortcut(_translate("MainWindow", "+"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_0.setShortcut(_translate("MainWindow", "0"))
        self.button_comma.setText(_translate("MainWindow", "."))
        self.button_comma.setShortcut(_translate("MainWindow", "."))
        self.button_help.setText(_translate("MainWindow", "?"))
        self.button_help.setShortcut(_translate("MainWindow", "?"))
        self.actionprofiling.setText(_translate("MainWindow", "profiling"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
